### ISSUE TITLE
Re-introduce redirects at cabled_array_hw2018/

### ISSUE THREAD

**Issue by amarburg** [oceanhackweek/oceanhackweek.github.io#1]
The klunky orignal repo structure (ala commit 1b13e14) was to fix a problem we introduced when we renamed the repo cabled_array_hw2018, containing the CAHW website, to CAHW2018_website.   Up to that change, the URL for the CAHW website was.  

http://oceanhackweek.github.io/cabled_array_hw2018/

but after the repo change it became 

http://oceanhackweek.github.io/CAHW2018_website/

and the old URL became invalid.  The suggested way to handle this is to set up an organizational site (this repo, which didn't exist until then) and add a subdir /cabled_array_hw2018/ _within the organizational site_ which contains page(s) which redirect to the new location.

Without those links, the original URL is broken again....

We got the idea from here:

https://shoehornwithteeth.com/ramblings/2016/12/redirecting-github-pages-after-renaming-a-repository/

**Comment by lsetiawan** [comment]
I am following the convention of geohackweek. Redirections will prevent me to be able to setup the website properly... So gotta think of a way that people can access the website from the last hackweek. :/

**Comment by amarburg** [comment]
Yeah, I haven't looked at your new structure (though the website look good, btw).   The actual redirection is pretty surgical ... make a special page at cabled_array_hw2018/index.html which 301's to the new web page.   Technically speaking that doesn't handle the 3-ish sub-pages, but it's a start.

**Comment by lsetiawan** [comment]
Resolved.
