### ISSUE TITLE
// in email mailto:, in ohw-team extension

### ISSUE THREAD

**Issue by emiliom** [oceanhackweek/oceanhackweek.github.io#133]
@abkfenris Your ohw-team code prefixes email addresses with `mailto://`. eg, [here](https://github.com/oceanhackweek/oceanhackweek.github.io/blob/source/_ext/ohw_team.py#L106). But isn't it supposed to be just `mailto:`, with no slashes?

**Comment by abkfenris** [comment]
Good catch, I'll fix that in a min.

**Comment by abkfenris** [comment]
And I forgot to check into a new branch, so I guess directly committing is a thing now.
