### ISSUE TITLE
Submodule clean-up

### ISSUE THREAD

**Issue by leewujung** [oceanhackweek/oceanhackweek.github.io#14]
Currently direct editing of the jekyll-spetral-theme repo under oceanhackweek.github.io is needed to change textual content of website. This seems to be against the logic of using the theme and also make it difficult to pull new changes from the original jekyll repo. Would be nice to clean it up so that maintenance of website content and theme submodule is separated.

**Comment by ocefpaf** [comment]
@leewujung if I understand the problem correctly the edits you are referring to are theme edits, right? If so we cannot keep theme and site separate. We would need to "bake" the theme into the site and ditch the submodule workflow. See https://github.com/oceanhackweek/oceanhackweek.github.io/pull/44 for a suggestion on that.

**Comment by emiliom** [comment]
Closing. #44 took care of it.
