### ISSUE TITLE
nbgitpuller instructions for R users

### ISSUE THREAD

**Issue by emiliom** [oceanhackweek/oceanhackweek.github.io#181]
Our current instructions for using `nbgitpuller` use a link that will take users into JupyterLab. For participants who intend to focus entirely on R, their normal Hub workflow would be to always select the R(studio) image and they'd never see Jupyter. I wonder if their experience clicking on our `nbgitpuller` link would lead to confusion. Should we add some additional text to minimize confusion?

For reference, this issue surface in [PR #170,](https://github.com/oceanhackweek/oceanhackweek.github.io/pull/179#issuecomment-1208302135)

**Comment by abkfenris** [comment]
Maybe for nbgitpuller and anywhere that we have Python/R specific instructions, we use [sphinx-design tabs](https://sphinx-design.readthedocs.io/en/pydata-theme/tabs.html) to highlight that there are two parallel options.

**Comment by emiliom** [comment]
I like that. It would provide a consistent presentation across the site, and in a way that may feel less cluttered.

**Comment by abkfenris** [comment]
Added in https://github.com/oceanhackweek/oceanhackweek.github.io/pull/191
