### ISSUE TITLE
Remove Jane Koh as steering committee member

### ISSUE THREAD

**Issue by asx-** [oceanhackweek/oceanhackweek.github.io#210]
Jane Koh is no longer a part of OHW and should have her tag removed as current steering committee member.

We should also think about whether or not we want a tag to notice previous steering committee members for their work.

**Comment by abkfenris** [comment]
How about 'Steering Committee - Emeritus'?

**Comment by asx-** [comment]
Yeah, I think that's fine. We can revisit this in a few years after members on the SC have come and gone, page looks cluttered, some other issue that's probably out there.
