### ISSUE TITLE
Preperation resources

### ISSUE THREAD

**Issue by abkfenris** [oceanhackweek/oceanhackweek.github.io#243]
I think our level of average experience coming in is a good bit higher than the [gapminders that we point to now](https://oceanhackweek.org/ohw23/applicants.html#q-i-am-proficient-in-matlab-other-languages-but-have-not-used-python-or-r-python-or-r-has-been-on-my-list-to-learn-how-can-i-make-my-application-be-stronger) for folks that need to level up.

It might be worth pointing to one or more of these resources, even if it's a suggestion to skim, just so when we talk about something, it's not their very first time introduction a topic that most participants know like Xarray and NetCDFs.

- [Pythia Foundations](https://foundations.projectpythia.org/landing-page.html)
- [An Introduction to Earth and Environmental Data Science](https://earth-env-data-science.github.io/intro)
- Data Carpentry - [Python for Atmosphere and Ocean Scientists](https://carpentries-lab.github.io/python-aos-lesson/)

**Comment by emiliom** [comment]
Do you suggest we edit this FAQ entry? https://oceanhackweek.org/ohw23/applicants.html#q-i-am-proficient-in-matlab-other-languages-but-have-not-used-python-or-r-python-or-r-has-been-on-my-list-to-learn-how-can-i-make-my-application-be-stronger

I think modifying the application form midway through the application period may be more problematic.

Also, we'd need to compile similar recommendations for R.

**Comment by abkfenris** [comment]
Ya that section. We had a quick conversation about including them in the application but decided it wasn't a requirement so it shouldn't make the form longer, more that we're trying to provide more support. Since it's not required, there shouldn't be a reason to block on needing R versions.
