### ISSUE TITLE
Serving OHW19 web site pages

### ISSUE THREAD

**Issue by emiliom** [oceanhackweek/oceanhackweek.github.io#52]
@ocefpaf and others: What would you suggest we do to serve the OHW19 web site and related materials? The OHW18 web site was archived as a repo, and the we can provide ready access to it at https://oceanhackweek.github.io/ohw2018/. We could do the same for OHW19, but I'd like to take a step back and explore options before continuing the proliferation of repositories. I saved the Jekyll files in a GitHub branch, https://github.com/oceanhackweek/oceanhackweek.github.io/tree/ohw19archive, and its associated, separate Jekyll sub-module theme repo at https://github.com/oceanhackweek/jekyll-spectral-theme.

Thanks.

**Comment by ocefpaf** [comment]
We can create branches for each year and I believe we can have a page per branch. I'll investigate this later today.

**Comment by emiliom** [comment]
Thanks! A gh page per branch for previous years would be very nice.

There's no rush.

**Comment by emiliom** [comment]
@ocefpaf any progress on this?

**Comment by ocefpaf** [comment]
Nope. I'll need some help to figure out what goes in each branch. Maybe @leewujung knows. Once the branches are created I can work on publishing them.

**Comment by emiliom** [comment]
> I'll need some help to figure out what goes in each branch.

Can you elaborate? I created the `ohw19archive` branch from master before we started making changes for ohw20. 

In this issue I'm only referring to the web site and pages associated with it; potentially that includes the wiki, but here I'm more concerned about the core web site pages hosted on this repo and previously (ohw19) in the jekyll sub-module repo, too.

**Comment by ocefpaf** [comment]
> Can you elaborate? I created the `ohw19archive` branch from master before we started making changes for ohw20.

Do you also want `ohw18archive` or just 19 is OK?

> In this issue I'm only referring to the web site and pages associated with it; potentially that includes the wiki, but here I'm more concerned about the core web site pages hosted on this repo and previously (ohw19) in the jekyll sub-module repo, too.

Yeah. It will be a bit complicated to build the old site. I'll probably have to "bake" the theme first to keep things in a single place and avoid cross-referencing to an external repo that may change/disappear.

**Comment by emiliom** [comment]
> Do you also want ohw18archive or just 19 is OK?

Just 19. The ohw18 site is currently available in its own repo, and it works. Let's not bother doing anything new with it in the near future.

Thanks!

**Comment by emiliom** [comment]
> I'm waiting for Aaron's response on doctr about the multiple branch publication. If he does not answer today I'll revert the changes and re-publish with the old setup.
The main challenge is that a .io site behaves differently from a normal gh-pages and publication from other branches and tags are not trivial.

> one alternative is to use the .io for a permanente page, not attached to any specific OHW year, and another repository with the pages for each year. That would change the ULR to https://oceanhackweek.github.io/OHW (current) and https://oceanhackweek.github.io/OHW/19 (archive), both can live on the same repo and the previous ones are just GH tags.

**Comment by emiliom** [comment]
I don't want to complicate this more than is necessary. Using branches for previous years was an alternative to the proliferation of repos. It sounds like the simplest approach is to fall back to creating a new `ohw19` repo to host the 2019 pages, with the sub-module repo still linked as it is now, or baked in if it won't take much of your time. That's what we're doing for ohw18, it works, and it's simple. 

The current year's web site then stays where it is, with the `.io` domain.

This summer we can rethink this if we have time. Right now, I think I've already taken too much of your time and my own OHW bandwidth is focusing on funding and the application process!

How does that sound?

**Comment by ocefpaf** [comment]
> I don't want to complicate this more than is necessary. Using branches for previous years was an alternative to the proliferation of repos. It sounds like the simplest approach is to fall back to creating a new `ohw19` repo to host the 2019 pages, with the sub-module repo still linked as it is now, or baked in if it won't take much of your time. That's what we're doing for ohw18, it works, and it's simple.

It will avoid the proliferation of repos in the long run. Right now the count would be +1 repo on both solutions. Next year will be +1 on your and 0 on my suggestion because we will be able to use branches. My main concern is the URL change.

> The current year's web site then stays where it is, with the `.io` domain.
> 
> This summer we can rethink this if we have time. Right now, I think I've already taken too much of your time and my own OHW bandwidth is focusing on funding and the application process!
> 
> How does that sound?

Sure. I'll reset the `doctr` config. If I hear from upstream I'll try it again.

**Comment by emiliom** [comment]
Thanks @ocefpaf!! It looks like everything is now set up:
https://oceanhackweek.github.io/ohw19/

I'd like to have this documented at least in an outline form. It's clear you've set up some CI things and strategies such as making the `source` branch effectively the main branch, which are making the magic happen. But I'd like to make sure information about this is disseminated beyond your brain and the code that implements this stuff (eg, [.travis.yml](../blob/source/.travis.yml)).

There's no rush to do this, but I suspect it'll be easier now that it's fresh in you head. Feel free to document any way that is convenient to you, such as bare-bones notes in this issue or a new markdown document where you don't worry much about formatting. I'll take it from there.

Once again, THANKS!

**Comment by ocefpaf** [comment]
> Thanks @ocefpaf!! It looks like everything is now set up:
> [oceanhackweek.github.io/ohw19](https://oceanhackweek.github.io/ohw19/)

I fixed the `subpath` to point to `ohw19` and "baked" the theme too so we could fix the various links that made reference to `base` instead of the `subpath`. I also fixed one reference to the `base` page as ohw18 and pointed it to the right `base/ohw2018` instead.

> I'd like to have this documented at least in an outline form. It's clear you've set up some CI things and strategies such as making the `source` branch effectively the main branch, which are making the magic happen. But I'd like to make sure information about this is disseminated beyond your brain and the code that implements this stuff (eg, [.travis.yml](../blob/source/.travis.yml)).

That is pretty much `doctr` docs: https://drdoctr.github.io/recipes.html#using-doctr-with-github-io-pages

I'm not sure it is worth documenting here instead of pointing it to upstream b/c if they change it we'll have stale docs. Actually that is what was preventing me from getting this right. I was doing the same I did last year but pretty much everything changed and I was outdated.

PS: can you check the ohw19 site and see if can stop any mistakes?

**Comment by emiliom** [comment]
Got it, thanks!

> PS: can you check the ohw19 site and see if can stop any mistakes?

Everything looks correct.

**Comment by asx-** [comment]
This became #83 and #109, both issues are closed and OHW19 website is publicly available. Closing issue.
