### ISSUE TITLE
Missing step from setup on OHW jupyterhub tutorial

### ISSUE THREAD

**Issue by callumrollo** [oceanhackweek/oceanhackweek.github.io#79]
The tutorial page that details how to work with tutorials on the OHW jupyterhub refers to a "Step 4" in the final paragraph

"you MUST complete Step 4 to save the files to your local machine if you would like continued access to them"

However, I cannot find Step 4 on the page.

https://oceanhackweek.github.io/ohw-resources/tutorials/getting_started/

**Comment by emiliom** [comment]
Moved it to https://github.com/oceanhackweek/ohw-resources/issues/18. Closing it here
