### ISSUE TITLE
Archive OHW20 site as new release

### ISSUE THREAD

**Issue by emiliom** [oceanhackweek/oceanhackweek.github.io#83]
Archive ohw20 web site as https://oceanhackweek.github.io/ohw20/, to get ready to start updating the site for ohw21.

The archive/release approach set up in 2020 was fleshed out in #52.

When this is completed, edit the current site to have good pointers to ohw20 materials (and ohw19 & ohw18).

**Comment by emiliom** [comment]
I issued a `ohw20` release just now. The system worked, and https://oceanhackweek.github.io/ohw20/ is now available. Though, it's worth noting that the associated [jekyll-diff GH action had a failure](https://github.com/oceanhackweek/oceanhackweek.github.io/actions/runs/605073126)

But maybe I should have created a projects page first, like https://oceanhackweek.github.io/ohw19/projects_2019.html? We can still do this by deleting the release then issuing it again when ready.

**Comment by abkfenris** [comment]
@emiliom '21 needs to be archived too.

**Comment by emiliom** [comment]
Moving the party to #109. Closing this issue
